import db from './db.js';

// "关于 Ling" 页面的默认内容（占位数据，超管可在后台修改）
const DEFAULT_PROFILE = {
  name: '凌渊',
  role: '全栈开发工程师',
  tagline: '用代码构建更聪明的产品',
  bio: '一名热爱技术与创造的全栈开发者，专注于 Web 应用、前端体验与数据可视化。相信好的产品来自对细节的执着，持续学习、持续输出。',
  location: '三亚 · 中国',
  email: 'hello@example.com',
  avatar_initial: 'L',
  hero: [
    'const developer = { name: "凌渊", role: "全栈开发工程师" };',
    'while (alive) { code(); learn(); ship(); }',
    'console.log("Hello, World! 👋")',
  ],
  skills: [
    { name: 'React / TypeScript', level: 90, note: '组件化架构 · Hooks · 状态管理' },
    { name: 'Node.js / 后端服务', level: 82, note: 'REST API · 微服务 · 数据库设计' },
    { name: 'Python / 数据分析', level: 78, note: 'Pandas · 可视化 · 自动化脚本' },
    { name: 'UI / 交互设计', level: 72, note: '设计系统 · 动效 · 响应式' },
    { name: 'DevOps / 云原生', level: 65, note: 'Docker · CI/CD · 云服务部署' },
    { name: '产品思维', level: 75, note: '需求分析 · 快速原型 · 用户研究' },
  ],
  projects: [
    {
      id: 1,
      title: 'Nebula Dashboard',
      description: '实时数据可视化大屏，支持多数据源接入与自定义图表编排，服务于企业运营监控场景。',
      tech: ['React', 'TypeScript', 'ECharts', 'WebSocket'],
      highlight: '3k+ 月活 · 20+ 企业客户',
      year: '2025',
    },
    {
      id: 2,
      title: 'FlowForge',
      description: '可视化工作流编排引擎，拖拽式节点设计，支持定时任务与 Webhook 触发，帮助团队自动化重复工作。',
      tech: ['Node.js', 'React', 'PostgreSQL', 'Docker'],
      highlight: '节省团队 40% 重复工时',
      year: '2025',
    },
    {
      id: 3,
      title: 'Pulse Bot',
      description: '开源社群运营机器人，自动聚合多平台消息、生成日报并推送，接入 200+ 技术社群。',
      tech: ['Python', 'Redis', 'Docker'],
      highlight: 'GitHub 500+ Star',
      year: '2024',
    },
    {
      id: 4,
      title: 'Lume Docs',
      description: '基于 AI 的文档协作工具，支持语义搜索与自动摘要，让团队知识沉淀更高效。',
      tech: ['React', 'LLM', 'Vector DB'],
      highlight: '内部 30+ 团队使用',
      year: '2024',
    },
  ],
  timeline: [
    {
      period: '2023 — 至今',
      title: '高级全栈工程师',
      org: '某互联网科技公司',
      description: '负责核心业务系统的架构设计与研发，主导前端工程化升级与性能优化，带领小组完成多个关键项目交付。',
    },
    {
      period: '2021 — 2023',
      title: '前端开发工程师',
      org: '某 SaaS 创业公司',
      description: '从 0 到 1 搭建产品前端，落地组件库与设计规范，推动数据可视化能力建设，支撑产品快速迭代。',
    },
    {
      period: '2019 — 2021',
      title: '软件工程师',
      org: '某软件服务公司',
      description: '参与企业级管理系统的前后端开发，覆盖订单、报表与权限模块，积累了扎实的工程实践基础。',
    },
  ],
  socials: [
    { label: 'GitHub', handle: '@yourname', href: 'https://github.com', icon: 'github' },
    { label: '邮箱', handle: 'hello@example.com', href: 'mailto:hello@example.com', icon: 'email' },
  ],
  contacts: [
    { label: '邮箱', value: 'hello@example.com', href: 'mailto:hello@example.com' },
    { label: 'GitHub', value: 'github.com/yourname', href: 'https://github.com' },
    { label: '所在城市', value: '三亚 · 中国', href: '' },
  ],
};

/**
 * 初始化数据库：
 * 1. 创建 ling_profile 表（幂等）
 * 2. 表为空时写入默认内容
 */
export async function initDatabase() {
  await db.exec(`
    CREATE TABLE IF NOT EXISTS ling_profile (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar(50) DEFAULT '',
      role varchar(80) DEFAULT '',
      tagline varchar(200) DEFAULT '',
      bio text DEFAULT '',
      location varchar(100) DEFAULT '',
      email varchar(100) DEFAULT '',
      avatar_initial varchar(10) DEFAULT '',
      hero jsonb DEFAULT '[]',
      skills jsonb DEFAULT '[]',
      projects jsonb DEFAULT '[]',
      timeline jsonb DEFAULT '[]',
      socials jsonb DEFAULT '[]',
      contacts jsonb DEFAULT '[]',
      updated_by integer,
      updated_at timestamp
    );
  `);

  const { rows } = await db.query('SELECT COUNT(*) AS c FROM ling_profile');
  if (Number(rows[0]?.c ?? 0) === 0) {
    await db.query(
      `INSERT INTO ling_profile
        (name, role, tagline, bio, location, email, avatar_initial,
         hero, skills, projects, timeline, socials, contacts, updated_by, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NULL, NOW())`,
      [
        DEFAULT_PROFILE.name,
        DEFAULT_PROFILE.role,
        DEFAULT_PROFILE.tagline,
        DEFAULT_PROFILE.bio,
        DEFAULT_PROFILE.location,
        DEFAULT_PROFILE.email,
        DEFAULT_PROFILE.avatar_initial,
        JSON.stringify(DEFAULT_PROFILE.hero),
        JSON.stringify(DEFAULT_PROFILE.skills),
        JSON.stringify(DEFAULT_PROFILE.projects),
        JSON.stringify(DEFAULT_PROFILE.timeline),
        JSON.stringify(DEFAULT_PROFILE.socials),
        JSON.stringify(DEFAULT_PROFILE.contacts),
      ]
    );
    console.log('[DB] ling_profile 表初始化完成（已写入默认内容）');
  }
}
